### ISSUE TITLE
Raven errors with django-perftools

### ISSUE THREAD

**Issue by vdboor** [disqus/django-perftools#4]
I'm getting the following errors:

```
Top level Sentry exception caught - failed creating log record
Request exceeeded execution time threshold: %s
Traceback (most recent call last):
  File "/Users/diederik/Sites/virtualenvs/test26/lib/python2.6/site-packages/raven/handlers/logging.py", line 68, in emit
    return self._emit(record)
  File "/Users/diederik/Sites/virtualenvs/test26/lib/python2.6/site-packages/raven/contrib/django/handlers.py", line 29, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/Users/diederik/Sites/virtualenvs/test26/lib/python2.6/site-packages/raven/handlers/logging.py", line 130, in _emit
    stack = self._get_targetted_stack(stack)
  File "/Users/diederik/Sites/virtualenvs/test26/lib/python2.6/site-packages/raven/handlers/logging.py", line 83, in _get_targetted_stack
    frame, lineno = item
ValueError: too many values to unpack

WARNING: Request exceeeded execution time threshold: http://127.0.0.1:8000/nl/admin/
```

This is my WSGI file:

```
from django.core.wsgi import get_wsgi_application
from raven.contrib.django.middleware.wsgi import Sentry
from perftools.middleware import SlowRequestLoggingMiddleware, QueryCountLoggingMiddleware

application = get_wsgi_application()
application = Sentry(application)
application = SlowRequestLoggingMiddleware(application, threshold=200) # in ms
application = QueryCountLoggingMiddleware(application, threshold=100)  # number of queries
```

I'm using:
- Raven 5.0 (also tried: 4.2.3)
- django-perftools 0.7.2
- Python 2.6 (sadly, production server runs CentOS 6.5)
- The app also uses `raven.contrib.django.middleware.SentryLogMiddleware`

Thanks in advance for any assistance or tips to solve this.

**Comment by vdboor** [comment]
Investigating it deeper, it seems that the error is triggered by the following `extra={...}` construct:

```
        self.logger.warning('Request exceeeded execution time threshold: %s', url, extra={
            'request': request,
            'view': culprit,
            'stack': frames,
            'url': url,
            'data': {
                'threshold': self.threshold,
            }
        })
```

When the `stack` argument value is simply `True`, the Raven error does not occur.

**Comment by dcramer** [comment]
@vdboor i believe the 'stack' value its passing is no longer in an acceptable format

**Comment by vdboor** [comment]
I'm a bit lost here. Would you be able to fix this?
